'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var mappings = [{
  'char': '€',
  'utf_8': '\u20AC',
  'misrender': 'â‚¬'
}, {
  'char': 'À',
  'utf_8': '\u00C0',
  'misrender': 'Ã€'
}, {
  'char': 'Á',
  'utf_8': '\u00C1',
  'misrender': 'Ã'
}, {
  'char': '‚',
  'utf_8': '\u201A',
  'misrender': 'â€š'
}, {
  'char': 'Â',
  'utf_8': '\u00C2',
  'misrender': 'Ã‚'
}, {
  'char': 'ƒ',
  'utf_8': '\u0192',
  'misrender': 'Æ’'
}, {
  'char': 'Ã',
  'utf_8': '\u00C3',
  'misrender': 'Ãƒ'
}, {
  'char': '„',
  'utf_8': '\u201E',
  'misrender': 'â€ž'
}, {
  'char': 'Ä',
  'utf_8': '\u00C4',
  'misrender': 'Ã„'
}, {
  'char': '…',
  'utf_8': '\u2026',
  'misrender': 'â€¦'
}, {
  'char': 'Å',
  'utf_8': '\u00C5',
  'misrender': 'Ã…'
}, {
  'char': '†',
  'utf_8': '\u2020',
  'misrender': 'â€'
}, {
  'char': 'Æ',
  'utf_8': '\u00C6',
  'misrender': 'Ã†'
}, {
  'char': '‡',
  'utf_8': '\u2021',
  'misrender': 'â€¡'
}, {
  'char': 'Ç',
  'utf_8': '\u00C7',
  'misrender': 'Ã‡'
}, {
  'char': 'ˆ',
  'utf_8': '\u02C6',
  'misrender': 'Ë†'
}, {
  'char': 'È',
  'utf_8': '\u00C8',
  'misrender': 'Ãˆ'
}, {
  'char': '‰',
  'utf_8': '\u2030',
  'misrender': 'â€°'
}, {
  'char': 'É',
  'utf_8': '\u00C9',
  'misrender': 'Ã‰'
}, {
  'char': 'Š',
  'utf_8': '\u0160',
  'misrender': 'Å'
}, {
  'char': 'Ê',
  'utf_8': '\u00CA',
  'misrender': 'ÃŠ'
}, {
  'char': '‹',
  'utf_8': '\u2039',
  'misrender': 'â€¹'
}, {
  'char': 'Ë',
  'utf_8': '\u00CB',
  'misrender': 'Ã‹'
}, {
  'char': 'Œ',
  'utf_8': '\u0152',
  'misrender': 'Å’'
}, {
  'char': 'Ì',
  'utf_8': '\u00CC',
  'misrender': 'ÃŒ'
}, {
  'char': 'Í',
  'utf_8': '\u00CD',
  'misrender': 'Ã'
}, {
  'char': 'Ž',
  'utf_8': '\u017D',
  'misrender': 'Å½'
}, {
  'char': 'Î',
  'utf_8': '\u00CE',
  'misrender': 'ÃŽ'
}, {
  'char': 'Ï',
  'utf_8': '\u00CF',
  'misrender': 'Ã'
}, {
  'char': 'Ð',
  'utf_8': '\u00D0',
  'misrender': 'Ã'
}, {
  'char': '‘',
  'utf_8': '\u2018',
  'misrender': 'â€˜'
}, {
  'char': 'Ñ',
  'utf_8': '\u00D1',
  'misrender': 'Ã‘'
}, {
  'char': '’',
  'utf_8': '\u2019',
  'misrender': 'â€™'
}, {
  'char': 'Ò',
  'utf_8': '\u00D2',
  'misrender': 'Ã’'
}, {
  'char': '“',
  'utf_8': '\u201C',
  'misrender': 'â€œ'
}, {
  'char': 'Ó',
  'utf_8': '\u00D3',
  'misrender': 'Ã“'
}, {
  'char': '”',
  'utf_8': '\u201D',
  'misrender': 'â€'
}, {
  'char': 'Ô',
  'utf_8': '\u00D4',
  'misrender': 'Ã”'
}, {
  'char': '•',
  'utf_8': '\u2022',
  'misrender': 'â€¢'
}, {
  'char': 'Õ',
  'utf_8': '\u00D5',
  'misrender': 'Ã•'
}, {
  'char': '–',
  'utf_8': '\u2013',
  'misrender': 'â€“'
}, {
  'char': 'Ö',
  'utf_8': '\u00D6',
  'misrender': 'Ã–'
}, {
  'char': '—',
  'utf_8': '\u2014',
  'misrender': 'â€”'
}, {
  'char': '×',
  'utf_8': '\u00D7',
  'misrender': 'Ã—'
}, {
  'char': '˜',
  'utf_8': '\u02DC',
  'misrender': 'Ëœ'
}, {
  'char': 'Ø',
  'utf_8': '\u00D8',
  'misrender': 'Ã˜'
}, {
  'char': '™',
  'utf_8': '\u2122',
  'misrender': 'â„¢'
}, {
  'char': 'Ù',
  'utf_8': '\u00D9',
  'misrender': 'Ã™'
}, {
  'char': 'š',
  'utf_8': '\u0161',
  'misrender': 'Å¡'
}, {
  'char': 'Ú',
  'utf_8': '\u00DA',
  'misrender': 'Ãš'
}, {
  'char': '›',
  'utf_8': '\u203A',
  'misrender': 'â€º'
}, {
  'char': 'Û',
  'utf_8': '\u00DB',
  'misrender': 'Ã›'
}, {
  'char': 'œ',
  'utf_8': '\u0153',
  'misrender': 'Å“'
}, {
  'char': 'Ü',
  'utf_8': '\u00DC',
  'misrender': 'Ãœ'
}, {
  'char': 'Ý',
  'utf_8': '\u00DD',
  'misrender': 'Ã'
}, {
  'char': 'ž',
  'utf_8': '\u017E',
  'misrender': 'Å¾'
}, {
  'char': 'Þ',
  'utf_8': '\u00DE',
  'misrender': 'Ãž'
}, {
  'char': 'Ÿ',
  'utf_8': '\u0178',
  'misrender': 'Å¸'
}, {
  'char': 'ß',
  'utf_8': '\u00DF',
  'misrender': 'ÃŸ'
}, {
  'char': '',
  'utf_8': '\u00A0',
  'misrender': 'Â'
}, {
  'char': 'à',
  'utf_8': '\u00E0',
  'misrender': 'Ã'
}, {
  'char': '¡',
  'utf_8': '\u00A1',
  'misrender': 'Â¡'
}, {
  'char': 'á',
  'utf_8': '\u00E1',
  'misrender': 'Ã¡'
}, {
  'char': '¢',
  'utf_8': '\u00A2',
  'misrender': 'Â¢'
}, {
  'char': 'â',
  'utf_8': '\u00E2',
  'misrender': 'Ã¢'
}, {
  'char': '£',
  'utf_8': '\u00A3',
  'misrender': 'Â£'
}, {
  'char': 'ã',
  'utf_8': '\u00E3',
  'misrender': 'Ã£'
}, {
  'char': '¤',
  'utf_8': '\u00A4',
  'misrender': 'Â¤'
}, {
  'char': 'ä',
  'utf_8': '\u00E4',
  'misrender': 'Ã¤'
}, {
  'char': '¥',
  'utf_8': '\u00A5',
  'misrender': 'Â¥'
}, {
  'char': 'å',
  'utf_8': '\u00E5',
  'misrender': 'Ã¥'
}, {
  'char': '¦',
  'utf_8': '\u00A6',
  'misrender': 'Â¦'
}, {
  'char': 'æ',
  'utf_8': '\u00E6',
  'misrender': 'Ã¦'
}, {
  'char': '§',
  'utf_8': '\u00A7',
  'misrender': 'Â§'
}, {
  'char': 'ç',
  'utf_8': '\u00E7',
  'misrender': 'Ã§'
}, {
  'char': '¨',
  'utf_8': '\u00A8',
  'misrender': 'Â¨'
}, {
  'char': 'è',
  'utf_8': '\u00E8',
  'misrender': 'Ã¨'
}, {
  'char': '©',
  'utf_8': '\u00A9',
  'misrender': 'Â©'
}, {
  'char': 'é',
  'utf_8': '\u00E9',
  'misrender': 'Ã©'
}, {
  'char': 'ª',
  'utf_8': '\u00AA',
  'misrender': 'Âª'
}, {
  'char': 'ê',
  'utf_8': '\u00EA',
  'misrender': 'Ãª'
}, {
  'char': '«',
  'utf_8': '\u00AB',
  'misrender': 'Â«'
}, {
  'char': 'ë',
  'utf_8': '\u00EB',
  'misrender': 'Ã«'
}, {
  'char': '¬',
  'utf_8': '\u00AC',
  'misrender': 'Â¬'
}, {
  'char': 'ì',
  'utf_8': '\u00EC',
  'misrender': 'Ã¬'
}, {
  'char': '­',
  'utf_8': '\u00AD',
  'misrender': 'Â­'
}, {
  'char': 'í',
  'utf_8': '\u00ED',
  'misrender': 'Ã­'
}, {
  'char': '®',
  'utf_8': '\u00AE',
  'misrender': 'Â®'
}, {
  'char': 'î',
  'utf_8': '\u00EE',
  'misrender': 'Ã®'
}, {
  'char': '¯',
  'utf_8': '\u00AF',
  'misrender': 'Â¯'
}, {
  'char': 'ï',
  'utf_8': '\u00EF',
  'misrender': 'Ã¯'
}, {
  'char': '°',
  'utf_8': '\u00B0',
  'misrender': 'Â°'
}, {
  'char': 'ð',
  'utf_8': '\u00F0',
  'misrender': 'Ã°'
}, {
  'char': '±',
  'utf_8': '\u00B1',
  'misrender': 'Â±'
}, {
  'char': 'ñ',
  'utf_8': '\u00F1',
  'misrender': 'Ã±'
}, {
  'char': '²',
  'utf_8': '\u00B2',
  'misrender': 'Â²'
}, {
  'char': 'ò',
  'utf_8': '\u00F2',
  'misrender': 'Ã²'
}, {
  'char': '³',
  'utf_8': '\u00B3',
  'misrender': 'Â³'
}, {
  'char': 'ó',
  'utf_8': '\u00F3',
  'misrender': 'Ã³'
}, {
  'char': '´',
  'utf_8': '\u00B4',
  'misrender': 'Â´'
}, {
  'char': 'ô',
  'utf_8': '\u00F4',
  'misrender': 'Ã´'
}, {
  'char': 'µ',
  'utf_8': '\u00B5',
  'misrender': 'Âµ'
}, {
  'char': 'õ',
  'utf_8': '\u00F5',
  'misrender': 'Ãµ'
}, {
  'char': '¶',
  'utf_8': '\u00B6',
  'misrender': 'Â¶'
}, {
  'char': 'ö',
  'utf_8': '\u00F6',
  'misrender': 'Ã¶'
}, {
  'char': '·',
  'utf_8': '\u00B7',
  'misrender': 'Â·'
}, {
  'char': '÷',
  'utf_8': '\u00F7',
  'misrender': 'Ã·'
}, {
  'char': '¸',
  'utf_8': '\u00B8',
  'misrender': 'Â¸'
}, {
  'char': 'ø',
  'utf_8': '\u00F8',
  'misrender': 'Ã¸'
}, {
  'char': '¹',
  'utf_8': '\u00B9',
  'misrender': 'Â¹'
}, {
  'char': 'ù',
  'utf_8': '\u00F9',
  'misrender': 'Ã¹'
}, {
  'char': 'º',
  'utf_8': '\u00BA',
  'misrender': 'Âº'
}, {
  'char': 'ú',
  'utf_8': '\u00FA',
  'misrender': 'Ãº'
}, {
  'char': '»',
  'utf_8': '\u00BB',
  'misrender': 'Â»'
}, {
  'char': 'û',
  'utf_8': '\u00FB',
  'misrender': 'Ã»'
}, {
  'char': '¼',
  'utf_8': '\u00BC',
  'misrender': 'Â¼'
}, {
  'char': 'ü',
  'utf_8': '\u00FC',
  'misrender': 'Ã¼'
}, {
  'char': '½',
  'utf_8': '\u00BD',
  'misrender': 'Â½'
}, {
  'char': 'ý',
  'utf_8': '\u00FD',
  'misrender': 'Ã½'
}, {
  'char': '¾',
  'utf_8': '\u00BE',
  'misrender': 'Â¾'
}, {
  'char': 'þ',
  'utf_8': '\u00FE',
  'misrender': 'Ã¾'
}, {
  'char': '¿',
  'utf_8': '\u00BF',
  'misrender': 'Â¿'
}, {
  'char': 'ÿ',
  'utf_8': '\u00FF',
  'misrender': 'Ã¿'
}];

class Utfu {
  constructor(opts) {
    for (let [k, v] in opts) {
      this[k] = v;
    }
  }

  hex(str) {
    if (typeof str !== 'string') throw new Error('utfu requires a string to process');
    mappings.forEach(mapping => {
      const hex = new RegExp(`${mapping.utf8}`, 'gu');
      str = str.replace(hex, mapping.char);
    });
    return str;
  }

  txt(str) {
    if (typeof str !== 'string') throw new Error('utfu requires a string to process');
    mappings.forEach(mapping => {
      const text = new RegExp(`${mapping.misrender}`, 'gu');
      str = str.replace(text, mapping.char);
    });
    return str;
  }

}

exports.default = Utfu;
//# sourceMappingURL=index.js.map
